import { TeamMember, Workstream, Deliverable, PTORequest, TimeEntry, Pod, Skill } from '@/types';

export const skills: Skill[] = [
  { id: '1', name: 'Financial Analysis', category: 'Finance' },
  { id: '2', name: 'Risk Management', category: 'Finance' },
  { id: '3', name: 'Data Analytics', category: 'Technology' },
  { id: '4', name: 'Project Management', category: 'Management' },
  { id: '5', name: 'Python', category: 'Technology' },
  { id: '6', name: 'SQL', category: 'Technology' },
  { id: '7', name: 'Tableau', category: 'Technology' },
  { id: '8', name: 'Power BI', category: 'Technology' },
  { id: '9', name: 'Regulatory Compliance', category: 'Compliance' },
  { id: '10', name: 'Client Relations', category: 'Management' },
  { id: '11', name: 'Process Optimization', category: 'Operations' },
  { id: '12', name: 'Strategic Planning', category: 'Management' },
];

export const workstreams: Workstream[] = [
  { id: 'ws1', name: 'Risk & Compliance', description: 'Regulatory compliance and risk assessment', leaderId: '2', color: '#D04A02' },
  { id: 'ws2', name: 'Data Migration', description: 'Core banking data migration', leaderId: '3', color: '#2563EB' },
  { id: 'ws3', name: 'Process Automation', description: 'Business process automation initiatives', leaderId: '4', color: '#059669' },
  { id: 'ws4', name: 'Client Onboarding', description: 'Digital client onboarding transformation', leaderId: '5', color: '#7C3AED' },
  { id: 'ws5', name: 'Testing & QA', description: 'Quality assurance and testing', leaderId: '6', color: '#DC2626' },
];

export const pods: Pod[] = [
  { id: 'pod1', name: 'Regulatory Team', workstreamId: 'ws1', leaderId: '7' },
  { id: 'pod2', name: 'Credit Risk Team', workstreamId: 'ws1', leaderId: '8' },
  { id: 'pod3', name: 'ETL Team', workstreamId: 'ws2', leaderId: '9' },
  { id: 'pod4', name: 'Data Quality Team', workstreamId: 'ws2', leaderId: '10' },
  { id: 'pod5', name: 'RPA Team', workstreamId: 'ws3', leaderId: '11' },
];

export const teamMembers: TeamMember[] = [
  { id: '1', name: 'Sarah Mitchell', email: 'sarah.mitchell@pwc.com', jobTitle: 'Partner', skills: ['12', '10', '4'], isContractor: false },
  { id: '2', name: 'James Wilson', email: 'james.wilson@pwc.com', jobTitle: 'Director', supervisorId: '1', workstreamId: 'ws1', skills: ['2', '9', '4'], isContractor: false },
  { id: '3', name: 'Emily Chen', email: 'emily.chen@pwc.com', jobTitle: 'Director', supervisorId: '1', workstreamId: 'ws2', skills: ['3', '5', '6'], isContractor: false },
  { id: '4', name: 'Michael Brown', email: 'michael.brown@pwc.com', jobTitle: 'Director', supervisorId: '1', workstreamId: 'ws3', skills: ['11', '4', '12'], isContractor: false },
  { id: '5', name: 'Lisa Park', email: 'lisa.park@pwc.com', jobTitle: 'Senior Manager', supervisorId: '1', workstreamId: 'ws4', skills: ['10', '4', '12'], isContractor: false },
  { id: '6', name: 'David Kim', email: 'david.kim@pwc.com', jobTitle: 'Senior Manager', supervisorId: '1', workstreamId: 'ws5', skills: ['3', '6', '4'], isContractor: false },
  { id: '7', name: 'Amanda Foster', email: 'amanda.foster@pwc.com', jobTitle: 'Senior Manager', supervisorId: '2', workstreamId: 'ws1', podId: 'pod1', skills: ['9', '2', '1'], isContractor: false },
  { id: '8', name: 'Robert Taylor', email: 'robert.taylor@pwc.com', jobTitle: 'Manager', supervisorId: '2', workstreamId: 'ws1', podId: 'pod2', skills: ['2', '1', '3'], isContractor: false },
  { id: '9', name: 'Jennifer Lee', email: 'jennifer.lee@pwc.com', jobTitle: 'Manager', supervisorId: '3', workstreamId: 'ws2', podId: 'pod3', skills: ['5', '6', '3'], isContractor: false },
  { id: '10', name: 'Chris Martinez', email: 'chris.martinez@pwc.com', jobTitle: 'Manager', supervisorId: '3', workstreamId: 'ws2', podId: 'pod4', skills: ['3', '7', '8'], isContractor: false },
  { id: '11', name: 'Nicole Adams', email: 'nicole.adams@pwc.com', jobTitle: 'Senior Manager', supervisorId: '4', workstreamId: 'ws3', podId: 'pod5', skills: ['11', '5', '4'], isContractor: false },
  { id: '12', name: 'Kevin Wright', email: 'kevin.wright@pwc.com', jobTitle: 'Senior Associate', supervisorId: '7', workstreamId: 'ws1', podId: 'pod1', skills: ['9', '1'], isContractor: false },
  { id: '13', name: 'Rachel Green', email: 'rachel.green@pwc.com', jobTitle: 'Senior Associate', supervisorId: '7', workstreamId: 'ws1', podId: 'pod1', skills: ['2', '9'], isContractor: false },
  { id: '14', name: 'Daniel Scott', email: 'daniel.scott@pwc.com', jobTitle: 'Associate', supervisorId: '8', workstreamId: 'ws1', podId: 'pod2', skills: ['1', '3'], isContractor: false },
  { id: '15', name: 'Maria Garcia', email: 'maria.garcia@pwc.com', jobTitle: 'Associate', supervisorId: '9', workstreamId: 'ws2', podId: 'pod3', skills: ['5', '6'], isContractor: false },
  { id: '16', name: 'Tom Harris', email: 'tom.harris@contractor.com', jobTitle: 'Contractor', supervisorId: '10', workstreamId: 'ws2', podId: 'pod4', skills: ['7', '8'], isContractor: true },
  { id: '17', name: 'Ashley Moore', email: 'ashley.moore@pwc.com', jobTitle: 'Senior Associate', supervisorId: '11', workstreamId: 'ws3', podId: 'pod5', skills: ['5', '11'], isContractor: false },
  { id: '18', name: 'Brian Johnson', email: 'brian.johnson@contractor.com', jobTitle: 'Contractor', supervisorId: '6', workstreamId: 'ws5', skills: ['3', '6'], isContractor: true },
  { id: '19', name: 'Sophia White', email: 'sophia.white@pwc.com', jobTitle: 'Manager', supervisorId: '5', workstreamId: 'ws4', skills: ['10', '4'], isContractor: false },
  { id: '20', name: 'Jason Black', email: 'jason.black@pwc.com', jobTitle: 'Associate', supervisorId: '19', workstreamId: 'ws4', skills: ['10', '3'], isContractor: false },
];

export const deliverables: Deliverable[] = [
  {
    id: 'd1',
    title: 'Regulatory Gap Analysis Report',
    description: 'Comprehensive analysis of current regulatory compliance gaps',
    workstreamId: 'ws1',
    ownerId: '7',
    partnerName: 'Sarah Mitchell',
    tdStakeholder: 'John Thompson',
    dueDate: new Date('2024-02-15'),
    partnerReviewDate: new Date('2024-02-10'),
    clientReviewDate: new Date('2024-02-13'),
    progress: 75,
    status: 'In Progress',
    risk: 'Medium',
    riskDescription: 'Awaiting client input on specific regulatory requirements',
    subtasks: [
      { id: 'st1', deliverableId: 'd1', title: 'Document current state', assigneeId: '12', completed: true },
      { id: 'st2', deliverableId: 'd1', title: 'Identify gaps', assigneeId: '13', completed: true },
      { id: 'st3', deliverableId: 'd1', title: 'Draft recommendations', assigneeId: '7', completed: false },
    ],
    comments: [
      { id: 'c1', deliverableId: 'd1', authorId: '7', content: 'Initial draft completed, need partner review', createdAt: new Date('2024-01-20') },
      { id: 'c2', deliverableId: 'd1', authorId: '1', content: 'Good progress, lets discuss in next sync', createdAt: new Date('2024-01-21') },
    ],
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-21'),
  },
  {
    id: 'd2',
    title: 'Data Migration Architecture Design',
    description: 'Technical architecture for core banking data migration',
    workstreamId: 'ws2',
    ownerId: '9',
    partnerName: 'Sarah Mitchell',
    tdStakeholder: 'Mike Chen',
    dueDate: new Date('2024-02-28'),
    partnerReviewDate: new Date('2024-02-20'),
    progress: 45,
    status: 'In Progress',
    risk: 'High',
    riskDescription: 'Complex legacy system integration challenges',
    subtasks: [
      { id: 'st4', deliverableId: 'd2', title: 'Source system analysis', assigneeId: '15', completed: true },
      { id: 'st5', deliverableId: 'd2', title: 'Target architecture design', assigneeId: '9', completed: false },
    ],
    comments: [],
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-18'),
  },
  {
    id: 'd3',
    title: 'Process Automation Roadmap',
    description: 'Strategic roadmap for RPA implementation',
    workstreamId: 'ws3',
    ownerId: '11',
    partnerName: 'Sarah Mitchell',
    tdStakeholder: 'Lisa Wang',
    dueDate: new Date('2024-03-10'),
    progress: 90,
    status: 'Under Review',
    risk: 'Low',
    subtasks: [],
    comments: [],
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-22'),
  },
  {
    id: 'd4',
    title: 'Client Onboarding UX Research',
    description: 'User experience research for digital onboarding',
    workstreamId: 'ws4',
    ownerId: '19',
    partnerName: 'Sarah Mitchell',
    tdStakeholder: 'Jennifer Park',
    dueDate: new Date('2024-02-05'),
    clientReviewDate: new Date('2024-02-03'),
    progress: 100,
    status: 'Completed',
    risk: 'Low',
    subtasks: [],
    comments: [],
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: 'd5',
    title: 'Test Strategy Document',
    description: 'Comprehensive testing strategy and approach',
    workstreamId: 'ws5',
    ownerId: '6',
    partnerName: 'Sarah Mitchell',
    tdStakeholder: 'David Lee',
    dueDate: new Date('2024-02-20'),
    partnerReviewDate: new Date('2024-02-15'),
    progress: 30,
    status: 'In Progress',
    risk: 'Medium',
    riskDescription: 'Resource constraints in QA team',
    subtasks: [
      { id: 'st6', deliverableId: 'd5', title: 'Define test scenarios', assigneeId: '18', completed: true },
      { id: 'st7', deliverableId: 'd5', title: 'Create test cases', assigneeId: '18', completed: false },
    ],
    comments: [],
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-19'),
  },
  {
    id: 'd6',
    title: 'Credit Risk Model Validation',
    description: 'Validation of credit risk scoring models',
    workstreamId: 'ws1',
    ownerId: '8',
    partnerName: 'Sarah Mitchell',
    tdStakeholder: 'Robert Kim',
    dueDate: new Date('2024-03-01'),
    progress: 15,
    status: 'In Progress',
    risk: 'Critical',
    riskDescription: 'Model documentation incomplete from client side',
    subtasks: [],
    comments: [],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-20'),
  },
];

export const ptoRequests: PTORequest[] = [
  {
    id: 'pto1',
    userId: '12',
    startDate: new Date('2024-02-01'),
    endDate: new Date('2024-02-05'),
    reason: 'Family vacation',
    backupPersonId: '13',
    status: 'Approved',
    approvedById: '7',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'pto2',
    userId: '15',
    startDate: new Date('2024-02-10'),
    endDate: new Date('2024-02-12'),
    reason: 'Personal time',
    backupPersonId: '16',
    status: 'Pending',
    createdAt: new Date('2024-01-22'),
  },
  {
    id: 'pto3',
    userId: '17',
    startDate: new Date('2024-02-20'),
    endDate: new Date('2024-02-23'),
    reason: 'Medical appointment',
    status: 'Pending',
    createdAt: new Date('2024-01-23'),
  },
];

export const timeEntries: TimeEntry[] = [
  { id: 'te1', userId: '12', date: new Date('2024-01-22'), hours: 8, deliverableId: 'd1', description: 'Gap analysis documentation' },
  { id: 'te2', userId: '12', date: new Date('2024-01-23'), hours: 8, deliverableId: 'd1', description: 'Stakeholder interviews' },
  { id: 'te3', userId: '12', date: new Date('2024-01-24'), hours: 6, deliverableId: 'd1', description: 'Report drafting' },
  { id: 'te4', userId: '12', date: new Date('2024-01-24'), hours: 2, description: 'Team meeting' },
];

// Current logged in user (for demo purposes)
export const currentUser = teamMembers.find(m => m.id === '7')!;
